// Reference data that doesn't change mid-event. Edit here, redeploy.

export const SPONSORS = [
  { name: 'Airia', tier: 'gold' }, { name: 'Amdocs', tier: 'gold' }, { name: 'Broadridge', tier: 'gold' },
  { name: 'Cognition AI (Organizations)', tier: 'gold' }, { name: 'ElevenLabs', tier: 'gold' },
  { name: 'EXL', tier: 'gold' }, { name: 'Hewlett Packard Enterprise', tier: 'gold' },
  { name: 'Kyndryl', tier: 'gold' }, { name: 'OutSystems', tier: 'gold' }, { name: 'Pometry', tier: 'gold' },
  { name: 'Prosci', tier: 'gold' }, { name: 'Rackspace Technology', tier: 'gold' }, { name: 'Sage', tier: 'gold' },
  { name: 'Salesforce', tier: 'gold' }, { name: 'Skan AI', tier: 'gold' }, { name: 'Temenos', tier: 'gold' },
  { name: 'Tieto', tier: 'gold' },
  { name: 'Adesso', tier: 'silver' }, { name: 'Alinia', tier: 'silver' }, { name: 'Atombit', tier: 'silver' },
  { name: 'Credera', tier: 'silver' }, { name: 'Element', tier: 'silver' }, { name: 'Flowable', tier: 'silver' },
  { name: 'Gradient Labs', tier: 'silver' }, { name: 'Moneyhub', tier: 'silver' }, { name: 'Worldline', tier: 'silver' },
  { name: 'Cogence AI', tier: 'exhibitor' }, { name: 'Creatio', tier: 'exhibitor' }, { name: 'ERI', tier: 'exhibitor' },
  { name: 'Impetus', tier: 'exhibitor' }, { name: 'NTT Data', tier: 'exhibitor' }, { name: 'Oxford Risk', tier: 'exhibitor' },
  { name: 'Smart Communications', tier: 'exhibitor' }, { name: 'tts digital adoption solutions', tier: 'exhibitor' },
  { name: 'NextWave Consulting', tier: 'panel-partner' }, { name: 'Started PR', tier: 'pr-partner' },
  { name: 'Forest Bikes', tier: 'transport-partner' },
];

export const ALIASES = {
  'Airia': ['Airia'], 'Amdocs': ['Amdocs', 'amdocs'], 'Broadridge': ['Broadridge'],
  'Cognition AI (Organizations)': ['Cognition AI', 'Cognition', 'Cognition.AI', 'cognition.ai'],
  'ElevenLabs': ['ElevenLabs', 'Eleven Labs'], 'EXL': ['EXL', 'EXL Service'],
  'Hewlett Packard Enterprise': ['Hewlett Packard Enterprise', 'HPE', 'Hewlett Packard'],
  'Kyndryl': ['Kyndryl'], 'OutSystems': ['OutSystems', 'Outsystems'],
  'Pometry': ['Pometry'], 'Prosci': ['Prosci'],
  'Rackspace Technology': ['Rackspace Technology', 'Rackspace'],
  'Sage': ['Sage'], 'Salesforce': ['Salesforce'],
  'Skan AI': ['Skan AI', 'Skan', 'SkanAI'], 'Temenos': ['Temenos'],
  'Tieto': ['Tieto', 'Tietoevry', 'TietoEVRY'], 'Adesso': ['Adesso', 'adesso'],
  'Alinia': ['Alinia'], 'Atombit': ['Atombit'], 'Credera': ['Credera'],
  'Element': ['Element', 'TryElement'], 'Flowable': ['Flowable'],
  'Gradient Labs': ['Gradient Labs', 'Gradient-Labs'], 'Moneyhub': ['Moneyhub', 'MoneyHub'],
  'Worldline': ['Worldline'], 'Cogence AI': ['Cogence AI', 'Cogence.AI', 'Cogence'],
  'Creatio': ['Creatio'], 'ERI': ['ERI'], 'Impetus': ['Impetus', 'Impetus Technologies'],
  'NTT Data': ['NTT Data', 'NTT DATA'], 'Oxford Risk': ['Oxford Risk'],
  'Smart Communications': ['Smart Communications'],
  'tts digital adoption solutions': ['tts', 'TTS', 'tts digital adoption solutions'],
  'NextWave Consulting': ['NextWave Consulting', 'NextWave'],
  'Started PR': ['Started PR'], 'Forest Bikes': ['Forest Bikes', 'HumanForest', 'Human Forest'],
};

export const SPONSOR_SESSIONS = [
  { sponsor: 'ElevenLabs', session: "Where Are We Now? The Great Reinvention of Banking" },
  { sponsor: 'Salesforce', session: "Beyond the Bot: Conquering Banking's Hardest Frontiers With Agentic AI" },
  { sponsor: 'Pometry', session: "What Banks Can Learn About Transformation From the Defence & Intelligence Communities" },
  { sponsor: 'Prosci', session: "Digital Investment Is Live. Why Isn't Adoption Keeping Up?" },
  { sponsor: 'EXL', session: "Reimagining Banking Operations Using Data & AI: From Contact Centres to Experience Centres" },
  { sponsor: 'Rackspace Technology', session: "Behind the Screens: How Banks Make Their Digital Backbone Tick" },
  { sponsor: 'Sage', session: "Embedded Finance & Invisible Services: Who Owns the Customer Now?" },
  { sponsor: 'Oxford Risk', session: "People, Purpose and Personalisation: The New CX in Banking" },
  { sponsor: 'Flowable', session: "Real AI: Operational Use Cases Delivering Impact Today" },
  { sponsor: 'Cognition AI (Organizations)', session: "Trust Is the Real Bottleneck: Implementing agentic workflows in Banking" },
  { sponsor: 'ElevenLabs', session: "What 22 Million AI Banking Calls Taught Us About Trust" },
  { sponsor: 'Gradient Labs', session: "The Future of Software Engineering" },
  { sponsor: 'Adesso', session: "From Ambition to Architecture: What Vision Really Demands" },
  { sponsor: 'Atombit', session: "Next-Gen CX Automation: Personalisation in Real Time" },
  { sponsor: 'Alinia', session: "The AI Act Reality Check: From Principle to Practice" },
  { sponsor: 'Temenos', session: "Tokenisation and the Reinvention of Value" },
  { sponsor: 'Amdocs', session: "From Automation to Autonomy: Transforming Banking Operations with Agentic GenAI" },
  { sponsor: 'Broadridge', session: "The Value Road Map to Become an AI-ready Bank" },
  { sponsor: 'Airia', session: "Out of the Shadows: A Strategic Framework for AI Governance in Financial Services" },
  { sponsor: 'Worldline', session: "The Moving Pound: Reinventing Payments and the Architecture of Value" },
  { sponsor: 'Moneyhub', session: "Banking the Next Transformation" },
  { sponsor: 'Hewlett Packard Enterprise', session: "Smart Models, Strict Rules: Navigating Risk in the Age of Generative AI" },
  { sponsor: 'Skan AI', session: "People Deposit Trust, Not Just Money" },
  { sponsor: 'Tieto', session: "Multi-Rail Banking at Scale: Beating Margin Through Volume" },
  { sponsor: 'Salesforce', session: "Building Trust-Ready Infrastructure: Powering Secure, Real-Time Banking with AI" },
  { sponsor: 'Sage', session: "Built to Last: Designing Bank Infrastructure That Earns Trust" },
  { sponsor: 'Kyndryl', session: "Permission to F**k up" },
  { sponsor: 'Kyndryl', session: "Cloud or Bust - Balancing Efficiency and Agility in Banking Technology" },
  { sponsor: 'Started PR', session: "Podcast Panel: The Agentic Bank: What's Really Working" },
  { sponsor: 'Credera', session: "From Output to Outcome: The Race to Reinvent Customer Communications" },
  { sponsor: 'Element', session: "Building Banks That Bend: AI, Infrastructure and the Adaptive Edge" },
  { sponsor: 'NextWave Consulting', session: "After Hours Live Lounge + Networking Drinks" },
];
